name: Public Release to npmjs.com

on:
  push:
    branches:
      - main

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          scope: "@affinidi"

      - name: Install dependencies
        run: npm ci

      - name: Run release
        run: npm run semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLIC_NPM_NODE_AUTH_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
