name: Public Release to npmjs.com

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          scope: "@affinidi"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:binary

      - name: Publish to npmjs.org
        run: npm publish --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLIC_NPM_NODE_AUTH_TOKEN}}
