name: tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libsecret-1-dev

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
